### ISSUE TITLE
idea / feature request: for multiple scaling stages - possible to stay in latent space? 

### ISSUE THREAD

**Issue by EricRollei** [shiimizu/ComfyUI-TiledDiffusion#7]
Thank you for your work, these are great upscaling nodes

I found that using two stages of 2x worked better than one pass with 4x upsampling.   Then I found that using mixture of diffusers first at 2x followed by multi-diffusion at 2x gave improved details.   At least that was my experience so far.  

However, in staged use, one must decode, then encode the latent which costs time and perhaps some quality loss in converting from latent to pixels space multiple times.   Is it possible to go from one stage to the next staying in the latent space?  Perhaps if the tile size is kept the same?  

Even better would be an iterative cycle setting - to allow users to set the final magnification and have the nodes run as many cycles as needed.

**Comment by 49RpK5dY** [comment]
You don't need to leave the latent space until the very end. Example workflow:
![workflow](https://github.com/shiimizu/ComfyUI-TiledDiffusion/assets/101150557/8e4446e7-de1e-40a0-bc32-a4db71c28da5)

You might have to though since latent upscale requires pretty high denoise and will produce some serious artifacts doe to prompt applying to each tile. So your choices are to use pixel upscale with lower denoise or apply controlnet which would also need a decoded image.
